import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

# 1. Page Configuration
st.set_page_config(page_title="AI Sentiment Pulse Pro", layout="wide")

st.title("AI Sentiment Pulse: Market Mood Dashboard")
st.markdown("Real-time sentiment analysis of AI industry news using **FinBERT**.")

# 2. Load the data generated by your GitHub Action
try:
    df = pd.read_csv('data/daily_sentiment.csv')
    
    # --- Top Metrics Row ---
    col1, col2, col3 = st.columns(3)
    avg_confidence = df['confidence'].mean() * 100
    total_news = len(df)
    dominant_mood = df['sentiment'].mode()[0]
    
    col1.metric("Dominant Market Mood", dominant_mood)
    col2.metric("Average AI Confidence", f"{avg_confidence:.1f}%")
    col3.metric("Articles Analyzed", total_news)

    st.divider()

    # --- Charts Section ---
    left_chart, right_chart = st.columns(2)

    with left_chart:
        st.subheader(" Sentiment Distribution")
        # Color-coded for professional look
        color_map = {'Positive': '#00CC96', 'Neutral': '#636EFA', 'Negative': '#EF553B'}
        fig_pie = px.pie(df, names='sentiment', color='sentiment', 
                         color_discrete_map=color_map, hole=0.4)
        st.plotly_chart(fig_pie, use_container_width=True)

    with right_chart:
        st.subheader(" AI Confidence per Sentiment")
        # Box plot shows the range of how 'sure' the model is
        fig_box = px.box(df, x="sentiment", y="confidence", color="sentiment",
                         color_discrete_map=color_map, points="all")
        st.plotly_chart(fig_box, use_container_width=True)

    # --- Raw Data Section with High-Level Details ---
    st.subheader(" Recent Headlines & FinBERT Analysis")
    # Displaying the dataframe with formatted confidence
    st.dataframe(
        df[['date', 'title', 'sentiment', 'confidence', 'source']].sort_values(by='date', ascending=False),
        column_config={
            "confidence": st.column_config.ProgressColumn(
                "AI Confidence",
                help="How sure FinBERT is about this sentiment",
                format="%.2f",
                min_value=0,
                max_value=1,
            ),
        },
        use_container_width=True,
        hide_index=True
    )

except Exception as e:
    st.error(f"Error loading data: {e}. Ensure 'data/daily_sentiment.csv' exists.")
